# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pantallazo_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#ui de la pantalla principal
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Pantalla_Inicio_PIA(object):
    def setupUi(self, Pantalla_Inicio_PIA):
        Pantalla_Inicio_PIA.setObjectName("Pantalla_Inicio_PIA")
        Pantalla_Inicio_PIA.resize(836, 600)
        Pantalla_Inicio_PIA.setMinimumSize(QtCore.QSize(836, 600))
        Pantalla_Inicio_PIA.setMaximumSize(QtCore.QSize(836, 600))
        Pantalla_Inicio_PIA.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Pantalla_Inicio_PIA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 741, 551))
        self.label.setStyleSheet("border: 1px solid #d0d0d0;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 30, 608, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_etiquetasmateriapia = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_etiquetasmateriapia.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_etiquetasmateriapia.setObjectName("verticalLayout_etiquetasmateriapia")
        self.lbl_materia = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_materia.setStyleSheet("text-align: center;\n"
"font: 75 18pt \"Trebuchet MS\";")
        self.lbl_materia.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_materia.setObjectName("lbl_materia")
        self.verticalLayout_etiquetasmateriapia.addWidget(self.lbl_materia)
        self.lbl_pia = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_pia.setStyleSheet("text-align: center;\n"
"font: 75 18pt \"Trebuchet MS\";")
        self.lbl_pia.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pia.setObjectName("lbl_pia")
        self.verticalLayout_etiquetasmateriapia.addWidget(self.lbl_pia)
        self.lbl_equipo = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lbl_equipo.setStyleSheet("font: 75 18pt \"Trebuchet MS\";")
        self.lbl_equipo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_equipo.setObjectName("lbl_equipo")
        self.verticalLayout_etiquetasmateriapia.addWidget(self.lbl_equipo)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(220, 280, 421, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_GO = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_GO.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_GO.setObjectName("gridLayout_GO")
        self.btn_go = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_go.setMinimumSize(QtCore.QSize(150, 50))
        self.btn_go.setMaximumSize(QtCore.QSize(150, 50))
        self.btn_go.setSizeIncrement(QtCore.QSize(10, 0))
        self.btn_go.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_go.setStyleSheet("border: 1px solid #d0d0d0;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 12pt \"Trebuchet MS\";")
        self.btn_go.setObjectName("btn_go")
        self.gridLayout_GO.addWidget(self.btn_go, 0, 0, 1, 1)
        Pantalla_Inicio_PIA.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Pantalla_Inicio_PIA)
        self.statusbar.setObjectName("statusbar")
        Pantalla_Inicio_PIA.setStatusBar(self.statusbar)

        self.retranslateUi(Pantalla_Inicio_PIA)
        QtCore.QMetaObject.connectSlotsByName(Pantalla_Inicio_PIA)

    def retranslateUi(self, Pantalla_Inicio_PIA):
        _translate = QtCore.QCoreApplication.translate
        Pantalla_Inicio_PIA.setWindowTitle(_translate("Pantalla_Inicio_PIA", "Producto Integrador de Aprendizaje"))
        self.lbl_materia.setText(_translate("Pantalla_Inicio_PIA", "VISUALIZACIÓN DE DATOS Y DESARROLLO DE ESCRITORIO"))
        self.lbl_pia.setText(_translate("Pantalla_Inicio_PIA", "PRODUCTO INTEGRADOR DE APRENDIZAJE"))
        self.lbl_equipo.setText(_translate("Pantalla_Inicio_PIA", "Equipo Azul"))
        self.btn_go.setText(_translate("Pantalla_Inicio_PIA", "GO"))
