# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comentarios_guardar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#ui ventana guardar

from PyQt5 import QtCore, QtWidgets


class Ui_Comentarios_Guardar(object):
    def __init__(self,nombre_grafica):
        self.nombre_grafica=nombre_grafica
    def setupUi(self, Comentarios_Guardar):
        Comentarios_Guardar.setObjectName("Comentarios_Guardar")
        Comentarios_Guardar.setEnabled(True)
        Comentarios_Guardar.resize(658, 265)
        Comentarios_Guardar.setMinimumSize(QtCore.QSize(658, 265))
        Comentarios_Guardar.setMaximumSize(QtCore.QSize(658, 265))
        Comentarios_Guardar.setStyleSheet("border: 1px solid #d0d0d0;\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.ipt_comentarios = QtWidgets.QTextEdit(Comentarios_Guardar)
        self.ipt_comentarios.setGeometry(QtCore.QRect(50, 50, 581, 111))
        self.ipt_comentarios.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"font: 12pt \"Trebuchet MS\";")
        self.ipt_comentarios.setObjectName("ipt_comentarios")

        self.btn_guardar = QtWidgets.QPushButton(Comentarios_Guardar)
        self.btn_guardar.setGeometry(QtCore.QRect(250, 220, 191, 31))
        self.btn_guardar.setObjectName("btn_guardar")
        self.lbl_titulo = QtWidgets.QLabel(Comentarios_Guardar)
        self.lbl_titulo.setGeometry(QtCore.QRect(50, 10, 580, 31))
        self.lbl_titulo.setStyleSheet("border: 0px solid #d0d0d0;\n"
"font: 75 bold 14pt \"Trebuchet MS\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_titulo.setObjectName("lbl_titulo")
        self.lbl_pregunta = QtWidgets.QLabel(Comentarios_Guardar)
        self.lbl_pregunta.setGeometry(QtCore.QRect(120, 170, 628, 31))
        self.lbl_pregunta.setStyleSheet("border: 0px solid #d0d0d0;\n"
"font: 75 bold 10pt \"Trebuchet MS\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.lbl_pregunta.setObjectName("lbl_pregunta")

        self.retranslateUi(Comentarios_Guardar)
        QtCore.QMetaObject.connectSlotsByName(Comentarios_Guardar)

    def retranslateUi(self, Comentarios_Guardar):
        _translate = QtCore.QCoreApplication.translate
        Comentarios_Guardar.setWindowTitle(_translate("Comentarios_Guardar", "Comentarios Gráfica"))
        self.ipt_comentarios.setHtml(_translate("Comentarios_Guardar", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Trebuchet MS\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btn_guardar.setText(_translate("Comentarios_Guardar", "Guardar"))
        self.lbl_titulo.setText(_translate("Comentarios_Guardar", f"Comentarios sobre la gráfica {self.nombre_grafica}."))
        self.lbl_pregunta.setText(_translate("Comentarios_Guardar", "¿DESEA GUARDAR LA CONFIGURACIÓN DE LA GRÁFICA Y SUS COMENTARIOS?"))
